### ISSUE TITLE
Fatal: failed to write genesis block: db.Get err: leveldb: not found init tendermint ...

### ISSUE THREAD

**Issue by skiny2015** [lianxiangcloud/lk-chain#11]
Execute ./start.sh init DataPath
Reporting an error：
Fatal: failed to write genesis block: db.Get err: leveldb: not found
init tendermint ...

**Comment by tangjiandeng** [comment]
https://github.com/lianxiangcloud/lk-chain/issues/7

**Comment by lianxiangcloud** [comment]
上面的是正解
