### ISSUE TITLE
使用eth_getTransactionReceipt获取收据，成功的交易响应的"status": "0x0"

### ISSUE THREAD

**Issue by qinheqing** [lianxiangcloud/lk-chain#21]
使用区块浏览器查询该交易：tx = "0x16509530a7c2046fb450ac31430cbc9c90f947757e02100c30151eb4e94f3477"
![image](https://user-images.githubusercontent.com/23715137/59262911-b9a0e300-8c72-11e9-9348-07e28bf58f37.png)

使用rpc请求钱包：
请求体：
{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x16509530a7c2046fb450ac31430cbc9c90f947757e02100c30151eb4e94f3477"],"id":1}

响应体：
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x21f194f8d352749e20202878cda5336498506c9368f73214e9de3c50e8ef2f1e",
        "blockNumber": "0x5615a",
        "contractAddress": null,
        "cumulativeGasUsed": "0x186a0",
        "from": "0xcc55cd0d3afd4c2419f014f8e8a29f0df7cb9284",
        "gasUsed": "0x186a0",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "root": "0x08e234dd0857de6d60446820cbe476ce843a5fa9b2179c54e5be976ff53af075",
        "status": "0x0",
        "to": "0x2e7e08fef8469f24392d7d95393fc129364b28cb",
        "transactionHash": "0x16509530a7c2046fb450ac31430cbc9c90f947757e02100c30151eb4e94f3477",
        "transactionIndex": "0x0"
    }
}

其中的 "status": "0x0" 按接口文档说明应该是失败的，是改用别的方法校验还是怎么操作呢，能给个提示吗

**Comment by tcy945** [comment]
可以加QQ群讨论：305824815

**Comment by lianxiangcloud** [comment]
status 值没有存储到ReceiptForStorage结构中，该问题已经修复与commit c6f51c0e97f1545c06f037a26e13d805db7f32b6

由于历史数据已经存储到本地db中，所以直接用最新代码编译后，只是最新的交易凭证生效。如果想修复历史数据中的status值，需要重新从0开始同步账本
