### ISSUE TITLE
创建本地钱包成功，但使用eth_signTransaction转账链克失败

### ISSUE THREAD

**Issue by kongjuyuansu** [lianxiangcloud/lk-chain#22]
如题，在unlock指定账号后，使用eth_signTransaction转账可以返回类似于这样的结果：
{"jsonrpc":"2.0","id":1,"result":{"raw":"0xf86e0185174876e800830186a094577cb6506b656cf92d4eef4a707c30629a5a30708716345785d8a0008082e3e6a0761e18a7e74a48708418fc7a8c5290bee87a5554cb4247e749c3230d41655e4aa023dc63311a4f24b9efda94485a803d03d109d3baf7fe0582b75c83af98a4f652","tx":{"nonce":"0x1","gasPrice":"0x174876e800","gas":"0x186a0","to":"0x577cb6506b656cf92d4eef4a707c30629a5a3070","value":"0x16345785d8a000","input":"0x","v":"0xe3e6","r":"0x761e18a7e74a48708418fc7a8c5290bee87a5554cb4247e749c3230d41655e4a","s":"0x23dc63311a4f24b9efda94485a803d03d109d3baf7fe0582b75c83af98a4f652","hash":"0xaa93424c180fe89adbfd519787dcb2a47683971795332f4812acc8d77da15aef"}}}
看似好像成功了，但很可惜查询对应的交易hash根本查不到，钱包余额也没用变动……这是咋回事呢，难道目前的节点没有转账的权限么？

**Comment by qinheqing** [comment]
web3.eth.signTransaction()这个方法是对交易进行签名，返回对象的raw属性可以用来通过web3.eth.sendSignedTransaction() 方法来发送交易。

**Comment by tcy945** [comment]
可以加QQ群讨论：305824815

**Comment by kongjuyuansu** [comment]
> web3.eth.signTransaction()这个方法是对交易进行签名，返回对象的raw属性可以用来通过web3.eth.sendSignedTransaction() 方法来发送交易。

意思是先要签名后再签名再发送么，原来是这样……我还以为一个方法就可以完成交易（尴尬）

**Comment by kongjuyuansu** [comment]
> web3.eth.signTransaction()这个方法是对交易进行签名，返回对象的raw属性可以用来通过web3.eth.sendSignedTransaction() 方法来发送交易。
试了下eth_sendSignedTransaction提示The method eth_sendSignedTransaction does not exist/is not available,貌似不支持……然后我就直接用eth_sendTransaction发送交易，成功了……确实是一个方法就可以完成交易，之前因为这里的doc文档里没有eth_sendTransaction只有eth_signTransaction，所以我还以为eth_signTransaction就是用来发送交易的，第一次接触区块链代码，土鳖了哈哈

**Comment by kongjuyuansu** [comment]
> web3.eth.signTransaction()这个方法是对交易进行签名，返回对象的raw属性可以用来通过web3.eth.sendSignedTransaction() 方法来发送交易。

试了下eth_sendSignedTransaction提示The method eth_sendSignedTransaction does not exist/is not available，貌似不支持……
然后我就直接用eth_sendTransaction发送交易，成功了……
确实是用一个方法就可以完成交易，之前因为这里的doc文档里没有eth_sendTransaction和eth_sendSignedTransaction只有eth_signTransaction，所以我还以为eth_signTransaction就是用来发送交易的，第一次接触区块链代码，土鳖了哈哈

**Comment by tangjiandeng** [comment]
https://lkwallet.github.io  我已经成功了

**Comment by kongjuyuansu** [comment]
> https://lkwallet.github.io 我已经成功了

哈哈，你动作很快，这个web版钱包也是可以的，我是想做个本地钱包，毕竟本地钱包才最安全，其实就是写个GUI套上去就行了，但易用性差，不知道有没有人愿意用

**Comment by pldinfo** [comment]
有没有学习群 学习
不要讨论买卖连克的

**Comment by pldinfo** [comment]
> https://lkwallet.github.io 我已经成功了

厉害 有没有学习群 学习一下

**Comment by tcy945** [comment]
可以加QQ群讨论：305824815

**Comment by lianxiangcloud** [comment]
@kongjuyuansu 棒棒的哈，关闭了
