### ISSUE TITLE
state.db.tar.gz和state.db_20190510.tar.gz都是损坏的压缩文件

### ISSUE THREAD

**Issue by tangjiandeng** [lianxiangcloud/lk-chain#7]
安装后的state.db.tar.gz或者git库的state.db_20190510.tar.gz压缩文件都是无法解压的损坏文件，跑不了

**Comment by lianxiangcloud** [comment]
需要安装git lfs
具体请参照 https://git-lfs.github.com/

**Comment by lianxiangcloud** [comment]
需要安装git lfs
具体请参照 https://git-lfs.github.com/

**Comment by lianxiangcloud** [comment]
需要安装git lfs
具体请参照 https://git-lfs.github.com/
安装完成后重新clone或者执行git lfs fetch
